#!/bin/bash

# Github actions has all: 'py37,py38,py39,py310'
# For faster runtime, you can choose subset here
TOX_ENVS='py37'

# Optionally run ruby based markdown lint locally
# After installing ruby:
#   gem install mdl -v 0.11.0
RUN_MDL=false

# Exit on failure
set -e

echo "tox:"
tox -e $TOX_ENVS --parallel
echo "--------------------------------"

echo "isort:"
isort --settings-file pyproject.toml .
echo "--------------------------------"

echo "black:"
black --config=pyproject.toml .
echo "--------------------------------"

echo "pflake8:"
pflake8 --config=pyproject.toml
echo "--------------------------------"

echo "codespell:"
codespell ./src ./tests
echo "--------------------------------"

if [ "$RUN_MDL" = true ] ; then
    echo "mdl:"
    mdl --style '.mdl-style.rb' .
    echo "--------------------------------"
fi

echo
echo "SUCCESS"