"""
This type stub file was generated by pyright.
"""

from typing import Any, Awaitable, Coroutine, TypeVar, Union

"""
Backport of the asyncio.runners"""
__all__ = ("run36", )
_T = TypeVar("_T")
def run36(main: Union[Coroutine[Any, None, _T], Awaitable[_T]], *, debug: bool = ...) -> _T:
    """Run a coroutine.
    This functi"""
    ...

